version: 2
jobs:
  build:
    
    working_directory: ~/SpringBootWebTest

    docker:
      - image: circleci/openjdk:8-jdk
      
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:

      - checkout

      - restore_cache:
          - SpringBootWebTest-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - SpringBootWebTest-
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: SpringBootWebTest-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: src/test/reports/SpringBootWebTest-0.0.1-SNAPSHOT.jar